CREATE TABLE IF NOT EXISTS webhooks (
  id TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  "event" TEXT NOT NULL,
  payload JSON NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
